[package]
name = "ogir-verifierd"
description = "Experimental OGIR verifier executable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
ogir-verifier = { path = "../../crates/ogir-verifier", version = "=0.0.0" }

[lints]
workspace = true
