[package]
name = "ogird"
description = "Experimental local OGIR agent executable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
ogir-agent = { path = "../../crates/ogir-agent" }

[lints]
workspace = true
